/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Alias Manager
 #	author : miyako
 #	2016/05/02
 #
 # --------------------------------------------------------------------------------*/



// --- Alias
void ALIAS_Create(sLONG_PTR *pResult, PackagePtr pParams);
void ALIAS_Resolve(sLONG_PTR *pResult, PackagePtr pParams);

typedef enum LinkType{
	LinkSymbolic = 0,
	LinkHard,
	LinkAlias
} LinkType;