/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Alias-Manager.h
 #	source generated by 4D Plugin Wizard
 #	Project : Alias Manager
 #	author : miyako
 #	2019/10/14
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ALIAS_MANAGER_H
#define PLUGIN_ALIAS_MANAGER_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "C_LONGINT.h"

#include <Cocoa/Cocoa.h>

#pragma mark -

void ALIAS_Create(PA_PluginParameters params);
void ALIAS_Resolve(PA_PluginParameters params);

typedef enum LinkType{
    LinkSymbolic = 0,
    LinkHard,
    LinkAlias
} LinkType;

int pathGetFSRefID(NSString *path, FSVolumeRefNum *volumeID, UInt32 *fileID);

int pathResolveFSRefID(FSVolumeRefNum volumeID, UInt32 fileID, C_TEXT &path);

#endif /* PLUGIN_ALIAS_MANAGER_H */
